Adjusting jshintrb to handle last_comment
When I upgraded from Rails 4.2.5.2 to 4.2.6 and ran our test suite, I
encountered the following:

```console
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::App...>
jshintrb-0.3.0/lib/jshintrb/jshinttask.rb:55:in `define'
jshintrb-0.3.0/lib/jshintrb/jshinttask.rb:49:in `initialize'
```

See #stereobooster/jshintrb/24 by @tomekn for a reference solution
against the origin.